Repository solid-connection/solid-connect-server, pull requests merged in 2024-12, with the labels that each got.

#118 chore: 호스팅 도메인 변경과 nginx 제거에 따른 전환
  .github/workflows/release.yml
  docker-compose.yml
  docs/nginx.conf
  src/main/java/com/example/solidconnection/config/cors/CorsPropertiesConfig.java
  src/main/java/com/example/solidconnection/config/cors/WebConfig.java
  src/main/java/com/example/solidconnection/config/security/SecurityConfiguration.java
Labels: infra

#122 chore: workflows/release 수정
  .github/workflows/release.yml
Labels: infra

#123 [RELEASE] 241216 릴리즈
  .github/workflows/release.yml
Labels: release

#129 chore: 오타 수정 및 개행 수정
  README.md
  local_compose_down.sh
  local_compose_up.sh
  src/main/java/com/example/solidconnection/config/cors/CorsPropertiesConfig.java
  src/main/java/com/example/solidconnection/siteuser/domain/SiteUser.java
Labels: refactor
