Repository solid-connection/solid-connect-server, pull requests merged in 2025-02, with the labels that each got.

#178 test: 지원서 관련 통합테스트 코드 추가
  src/test/java/com/example/solidconnection/application/service/ApplicationQueryServiceTest.java
  src/test/java/com/example/solidconnection/application/service/ApplicationSubmissionServiceTest.java
  src/test/java/com/example/solidconnection/support/integration/BaseIntegrationTest.java
Labels: test

#183 refactor: TokenProvider 에서 각 토큰에 대한 로직을 캡슐화
  src/main/java/com/example/solidconnection/auth/domain/TokenType.java
  src/main/java/com/example/solidconnection/auth/service/AuthService.java
  src/main/java/com/example/solidconnection/auth/service/AuthTokenProvider.java
  src/main/java/com/example/solidconnection/auth/service/SignInService.java
  src/main/java/com/example/solidconnection/auth/service/SignUpService.java
  src/main/java/com/example/solidconnection/auth/service/SignUpTokenProvider.java
  src/main/java/com/example/solidconnection/auth/service/TokenProvider.java
  src/main/java/com/example/solidconnection/auth/service/TokenValidator.java
  src/main/java/com/example/solidconnection/custom/security/filter/SignOutCheckFilter.java
  src/test/java/com/example/solidconnection/auth/service/AuthTokenProviderTest.java
  src/test/java/com/example/solidconnection/auth/service/SignUpTokenProviderTest.java
  src/test/java/com/example/solidconnection/auth/service/TokenProviderTest.java
  src/test/java/com/example/solidconnection/custom/security/filter/SignOutCheckFilterTest.java
  src/test/java/com/example/solidconnection/e2e/ApplicantsQueryTest.java
  src/test/java/com/example/solidconnection/e2e/MyPageTest.java
  src/test/java/com/example/solidconnection/e2e/MyPageUpdateTest.java
  src/test/java/com/example/solidconnection/e2e/SignInTest.java
  src/test/java/com/example/solidconnection/e2e/SignUpTest.java
  src/test/java/com/example/solidconnection/e2e/UniversityDetailTest.java
  src/test/java/com/example/solidconnection/e2e/UniversityLikeTest.java
  src/test/java/com/example/solidconnection/e2e/UniversityRecommendTest.java
  src/test/java/com/example/solidconnection/e2e/UniversitySearchTest.java
Labels: refactor

#184 feat: 애플 인증 구현
  src/main/java/com/example/solidconnection/auth/client/AppleOAuthClient.java
  src/main/java/com/example/solidconnection/auth/client/AppleOAuthClientSecretProvider.java
  src/main/java/com/example/solidconnection/auth/client/ApplePublicKeyProvider.java
  src/main/java/com/example/solidconnection/auth/client/KakaoOAuthClient.java
  src/main/java/com/example/solidconnection/auth/controller/AuthController.java
  src/main/java/com/example/solidconnection/auth/dto/SignInResponse.java
  src/main/java/com/example/solidconnection/auth/dto/SignUpRequest.java
  src/main/java/com/example/solidconnection/auth/dto/SignUpResponse.java
  src/main/java/com/example/solidconnection/auth/dto/kakao/FirstAccessResponse.java
  src/main/java/com/example/solidconnection/auth/dto/kakao/KakaoCodeRequest.java
  src/main/java/com/example/solidconnection/auth/dto/kakao/KakaoOauthResponse.java
  src/main/java/com/example/solidconnection/auth/dto/oauth/AppleTokenDto.java
  src/main/java/com/example/solidconnection/auth/dto/oauth/AppleUserInfoDto.java
  src/main/java/com/example/solidconnection/auth/dto/oauth/KakaoTokenDto.java
  src/main/java/com/example/solidconnection/auth/dto/oauth/KakaoUserInfoDto.java
  src/main/java/com/example/solidconnection/auth/dto/oauth/OAuthCodeRequest.java
  src/main/java/com/example/solidconnection/auth/dto/oauth/OAuthResponse.java
  src/main/java/com/example/solidconnection/auth/dto/oauth/OAuthSignInResponse.java
  src/main/java/com/example/solidconnection/auth/dto/oauth/OAuthUserInfoDto.java
  src/main/java/com/example/solidconnection/auth/dto/oauth/SignUpPrepareResponse.java
  src/main/java/com/example/solidconnection/auth/service/SignInService.java
  src/main/java/com/example/solidconnection/auth/service/SignUpTokenProvider.java
  src/main/java/com/example/solidconnection/auth/service/TokenValidator.java
  src/main/java/com/example/solidconnection/auth/service/oauth/AppleOAuthService.java
  src/main/java/com/example/solidconnection/auth/service/oauth/KakaoOAuthService.java
  src/main/java/com/example/solidconnection/auth/service/oauth/OAuthService.java
  src/main/java/com/example/solidconnection/auth/service/oauth/OAuthSignUpService.java
  src/main/java/com/example/solidconnection/auth/service/oauth/SignUpTokenProvider.java
  src/main/java/com/example/solidconnection/config/client/AppleOAuthClientProperties.java
  src/main/java/com/example/solidconnection/config/client/KakaoOAuthClientProperties.java
  src/main/java/com/example/solidconnection/config/client/RestTemplateConfig.java
  src/main/java/com/example/solidconnection/custom/exception/ErrorCode.java
  src/main/java/com/example/solidconnection/util/JwtUtils.java
  src/test/java/com/example/solidconnection/auth/service/SignInServiceTest.java
  src/test/java/com/example/solidconnection/auth/service/SignUpTokenProviderTest.java
  src/test/java/com/example/solidconnection/auth/service/oauth/SignUpTokenProviderTest.java
  src/test/java/com/example/solidconnection/e2e/DynamicFixture.java
  src/test/java/com/example/solidconnection/e2e/SignInTest.java
  src/test/java/com/example/solidconnection/e2e/SignUpTest.java
Labels: feature

#186 refactor: 사용하지 않을 컬럼 제거
  src/main/java/com/example/solidconnection/application/service/ApplicationSubmissionService.java
  src/main/java/com/example/solidconnection/score/domain/GpaScore.java
  src/main/java/com/example/solidconnection/score/domain/LanguageTestScore.java
  src/main/java/com/example/solidconnection/score/dto/GpaScoreRequest.java
  src/main/java/com/example/solidconnection/score/dto/GpaScoreStatus.java
  src/main/java/com/example/solidconnection/score/dto/LanguageTestScoreRequest.java
  src/main/java/com/example/solidconnection/score/dto/LanguageTestScoreStatus.java
  src/main/java/com/example/solidconnection/score/dto/LanguageTestScoreStatusResponse.java
  src/main/java/com/example/solidconnection/score/service/ScoreService.java
  src/main/resources/db/migration/V4__remove_issue_date_columns.sql
  src/test/java/com/example/solidconnection/application/service/ApplicationSubmissionServiceTest.java
  src/test/java/com/example/solidconnection/score/service/ScoreServiceTest.java
  src/test/java/com/example/solidconnection/support/integration/BaseIntegrationTest.java
Labels: refactor

#188 feat: 이메일 인증 구현
  src/main/java/com/example/solidconnection/auth/controller/AuthController.java
  src/main/java/com/example/solidconnection/auth/dto/EmailSignInRequest.java
  src/main/java/com/example/solidconnection/auth/dto/EmailSignUpTokenRequest.java
  src/main/java/com/example/solidconnection/auth/dto/EmailSignUpTokenResponse.java
  src/main/java/com/example/solidconnection/auth/dto/SignUpRequest.java
  src/main/java/com/example/solidconnection/auth/service/CommonSignUpTokenProvider.java
  src/main/java/com/example/solidconnection/auth/service/EmailSignInService.java
  src/main/java/com/example/solidconnection/auth/service/EmailSignUpService.java
  src/main/java/com/example/solidconnection/auth/service/EmailSignUpTokenProvider.java
  src/main/java/com/example/solidconnection/auth/service/SignUpService.java
  src/main/java/com/example/solidconnection/auth/service/oauth/AppleOAuthService.java
  src/main/java/com/example/solidconnection/auth/service/oauth/KakaoOAuthService.java
  src/main/java/com/example/solidconnection/auth/service/oauth/OAuthService.java
  src/main/java/com/example/solidconnection/auth/service/oauth/OAuthSignUpService.java
  src/main/java/com/example/solidconnection/auth/service/oauth/OAuthSignUpTokenProvider.java
  src/main/java/com/example/solidconnection/config/security/SecurityConfiguration.java
  src/main/java/com/example/solidconnection/custom/exception/ErrorCode.java
  src/main/java/com/example/solidconnection/siteuser/domain/AuthType.java
  src/main/java/com/example/solidconnection/siteuser/domain/SiteUser.java
  src/main/resources/db/migration/V5__add_password_column.sql
  src/test/java/com/example/solidconnection/auth/service/EmailSignInServiceTest.java
  src/test/java/com/example/solidconnection/auth/service/oauth/OAuthSignUpTokenProviderTest.java
  src/test/java/com/example/solidconnection/e2e/SignUpTest.java
Labels: feature

#187 refactor: 입력 형식과 관련된 검증은 Dto 내부에서 하게 한다.
  src/main/java/com/example/solidconnection/application/dto/ApplyRequest.java
  src/main/java/com/example/solidconnection/application/dto/UniversityChoiceRequest.java
  src/main/java/com/example/solidconnection/application/service/ApplicationSubmissionService.java
  src/main/java/com/example/solidconnection/custom/exception/ErrorCode.java
  src/main/java/com/example/solidconnection/custom/validation/annotation/ValidUniversityChoice.java
  src/main/java/com/example/solidconnection/custom/validation/validator/ValidUniversityChoiceValidator.java
  src/test/java/com/example/solidconnection/application/service/ApplicationSubmissionServiceTest.java
  src/test/java/com/example/solidconnection/custom/validation/validator/ValidUniversityChoiceValidatorTest.java
Labels: refactor

#192 feat: 관리자 role 추가
  src/main/java/com/example/solidconnection/config/security/SecurityConfiguration.java
  src/main/java/com/example/solidconnection/custom/exception/ErrorCode.java
  src/main/java/com/example/solidconnection/custom/security/authentication/JwtAuthentication.java
  src/main/java/com/example/solidconnection/custom/security/filter/ExceptionHandlerFilter.java
  src/main/java/com/example/solidconnection/custom/security/userdetails/SecurityRoleMapper.java
  src/main/java/com/example/solidconnection/custom/security/userdetails/SiteUserDetails.java
  src/main/java/com/example/solidconnection/type/Role.java
  src/main/resources/db/migration/V6__add_admin_to_role_enum.sql
  src/test/java/com/example/solidconnection/custom/security/filter/ExceptionHandlerFilterTest.java
  src/test/java/com/example/solidconnection/custom/security/userdetails/SiteUserDetailsServiceTest.java
  src/test/java/com/example/solidconnection/custom/security/userdetails/SiteUserDetailsTest.java
Labels: feature

#195 refactor: 내 정보와 대학 관련 api 수정
  src/main/java/com/example/solidconnection/auth/service/EmailSignInService.java
  src/main/java/com/example/solidconnection/custom/exception/ErrorCode.java
  src/main/java/com/example/solidconnection/siteuser/controller/SiteUserController.java
  src/main/java/com/example/solidconnection/siteuser/service/SiteUserService.java
  src/main/java/com/example/solidconnection/university/controller/UniversityController.java
  src/main/java/com/example/solidconnection/university/service/UniversityLikeService.java
  src/main/resources/data.sql
  src/test/java/com/example/solidconnection/e2e/MyPageTest.java
  src/test/java/com/example/solidconnection/e2e/MyPageUpdateTest.java
  src/test/java/com/example/solidconnection/e2e/UniversityDetailTest.java
  src/test/java/com/example/solidconnection/e2e/UniversityLikeTest.java
  src/test/java/com/example/solidconnection/e2e/UniversityRecommendTest.java
  src/test/java/com/example/solidconnection/e2e/UniversitySearchTest.java
  src/test/java/com/example/solidconnection/siteuser/service/SiteUserServiceTest.java
  src/test/java/com/example/solidconnection/university/service/UniversityLikeServiceTest.java
Labels: refactor

#201 fix: 인증과 관련되어 리졸버와 컨트롤러 인자에서 발생한 이슈 해결
  src/main/java/com/example/solidconnection/auth/controller/AuthController.java
  src/main/java/com/example/solidconnection/custom/resolver/AuthorizedUser.java
  src/main/java/com/example/solidconnection/custom/resolver/AuthorizedUserResolver.java
  src/main/java/com/example/solidconnection/custom/resolver/ExpiredToken.java
  src/main/java/com/example/solidconnection/custom/resolver/ExpiredTokenResolver.java
  src/main/java/com/example/solidconnection/custom/security/authentication/ExpiredTokenAuthentication.java
  src/main/java/com/example/solidconnection/custom/security/provider/ExpiredTokenAuthenticationProvider.java
  src/main/java/com/example/solidconnection/university/controller/UniversityController.java
  src/test/java/com/example/solidconnection/custom/resolver/AuthorizedUserResolverTest.java
Labels: bug

#196 refactor: 커뮤니티, 지원, 성적 관련 api 수정
  src/main/java/com/example/solidconnection/application/controller/ApplicationController.java
  src/main/java/com/example/solidconnection/community/board/controller/BoardController.java
  src/main/java/com/example/solidconnection/community/comment/controller/CommentController.java
  src/main/java/com/example/solidconnection/community/comment/dto/CommentCreateRequest.java
  src/main/java/com/example/solidconnection/community/comment/service/CommentService.java
  src/main/java/com/example/solidconnection/community/post/controller/PostController.java
  src/main/java/com/example/solidconnection/community/post/dto/PostCreateRequest.java
  src/main/java/com/example/solidconnection/community/post/service/PostCommandService.java
  src/main/java/com/example/solidconnection/community/post/service/PostLikeService.java
  src/main/java/com/example/solidconnection/community/post/service/PostQueryService.java
  src/main/java/com/example/solidconnection/score/controller/ScoreController.java
  src/main/java/com/example/solidconnection/score/dto/GpaScoreRequest.java
  src/main/java/com/example/solidconnection/score/dto/LanguageTestScoreRequest.java
  src/main/java/com/example/solidconnection/score/service/ScoreService.java
  src/test/java/com/example/solidconnection/community/comment/service/CommentServiceTest.java
  src/test/java/com/example/solidconnection/community/post/service/PostCommandServiceTest.java
  src/test/java/com/example/solidconnection/community/post/service/PostLikeServiceTest.java
  src/test/java/com/example/solidconnection/community/post/service/PostQueryServiceTest.java
  src/test/java/com/example/solidconnection/concurrency/PostLikeCountConcurrencyTest.java
  src/test/java/com/example/solidconnection/e2e/ApplicantsQueryTest.java
  src/test/java/com/example/solidconnection/score/service/ScoreServiceTest.java
Labels: refactor

#212 feat: university_info_for_apply 테이블 details 컬럼 길이 증가
  src/main/java/com/example/solidconnection/university/domain/UniversityInfoForApply.java
  src/main/resources/db/migration/V7__expand_details_column_length.sql
Labels: feature

#213 feat: 마이페이지 조회 시 authType 추가
  src/main/java/com/example/solidconnection/siteuser/dto/MyPageResponse.java
  src/test/java/com/example/solidconnection/siteuser/service/SiteUserServiceTest.java
Labels: feature

#210 fix: 유효하지 않은 토큰으로 api 요청 시 500 error 발생 버그 수정
  src/main/java/com/example/solidconnection/config/security/SecurityConfiguration.java
  src/main/java/com/example/solidconnection/custom/exception/CustomAccessDeniedHandler.java
  src/main/java/com/example/solidconnection/custom/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/solidconnection/custom/response/ErrorResponse.java
  src/main/java/com/example/solidconnection/custom/security/filter/ExceptionHandlerFilter.java
  src/test/java/com/example/solidconnection/custom/exception/CustomAccessDeniedHandlerTest.java
  src/test/java/com/example/solidconnection/custom/exception/CustomAuthenticationEntryPointTest.java
  src/test/java/com/example/solidconnection/custom/security/filter/ExceptionHandlerFilterTest.java
Labels: bug

#214 [RELEASE] 250215 릴리즈
  src/main/java/com/example/solidconnection/config/security/SecurityConfiguration.java
  src/main/java/com/example/solidconnection/custom/exception/CustomAccessDeniedHandler.java
  src/main/java/com/example/solidconnection/custom/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/solidconnection/custom/response/ErrorResponse.java
  src/main/java/com/example/solidconnection/custom/security/filter/ExceptionHandlerFilter.java
  src/test/java/com/example/solidconnection/custom/exception/CustomAccessDeniedHandlerTest.java
  src/test/java/com/example/solidconnection/custom/exception/CustomAuthenticationEntryPointTest.java
  src/test/java/com/example/solidconnection/custom/security/filter/ExceptionHandlerFilterTest.java
Labels: release

#206 chore: stage CD 스크립트 작성
  .github/workflows/prod-cd.yml
  .github/workflows/stage-cd.yml
Labels: infra

#220 fix: 지원 내역 조회 시 캐시 갱신 문제 임시 해결
  src/main/java/com/example/solidconnection/application/service/ApplicationQueryService.java
  src/main/java/com/example/solidconnection/application/service/ApplicationSubmissionService.java
Labels: bug

#227 fix: 프로필 수정 API에서 닉네임, 이미지 부분 업데이트 가능하도록 수정
  src/main/java/com/example/solidconnection/siteuser/controller/SiteUserController.java
  src/main/java/com/example/solidconnection/siteuser/service/SiteUserService.java
  src/test/java/com/example/solidconnection/siteuser/service/SiteUserServiceTest.java
Labels: bug

#207 feat: 관리자 페이지 학점 인증 관리 api 추가
  src/main/generated/com/example/solidconnection/application/domain/QApplication.java
  src/main/generated/com/example/solidconnection/siteuser/domain/QSiteUser.java
  src/main/generated/com/example/solidconnection/university/domain/QUniversityInfoForApply.java
  src/main/java/com/example/solidconnection/admin/controller/AdminScoreController.java
  src/main/java/com/example/solidconnection/admin/dto/GpaResponse.java
  src/main/java/com/example/solidconnection/admin/dto/GpaScoreResponse.java
  src/main/java/com/example/solidconnection/admin/dto/GpaScoreSearchResponse.java
  src/main/java/com/example/solidconnection/admin/dto/GpaScoreStatusResponse.java
  src/main/java/com/example/solidconnection/admin/dto/GpaScoreUpdateRequest.java
  src/main/java/com/example/solidconnection/admin/dto/ScoreSearchCondition.java
  src/main/java/com/example/solidconnection/admin/dto/SiteUserResponse.java
  src/main/java/com/example/solidconnection/admin/service/AdminGpaScoreService.java
  src/main/java/com/example/solidconnection/application/service/ApplicationSubmissionService.java
  src/main/java/com/example/solidconnection/custom/exception/ErrorCode.java
  src/main/java/com/example/solidconnection/custom/response/PageResponse.java
  src/main/java/com/example/solidconnection/custom/validation/annotation/RejectedReasonRequired.java
  src/main/java/com/example/solidconnection/custom/validation/validator/RejectedReasonValidator.java
  src/main/java/com/example/solidconnection/score/domain/GpaScore.java
  src/main/java/com/example/solidconnection/score/repository/GpaScoreRepository.java
  src/main/java/com/example/solidconnection/score/repository/custom/GpaScoreFilterRepository.java
  src/main/java/com/example/solidconnection/score/repository/custom/GpaScoreFilterRepositoryImpl.java
  src/main/java/com/example/solidconnection/util/PagingUtils.java
  src/test/java/com/example/solidconnection/admin/service/GpaScoreVerificationAdminServiceTest.java
  src/test/java/com/example/solidconnection/custom/validation/validator/RejectedReasonValidatorTest.java
  src/test/java/com/example/solidconnection/util/PagingUtilsTest.java
Labels: feature

#230 fix: 최신 지원서만 조회되도록 수정
  src/main/java/com/example/solidconnection/application/repository/ApplicationRepository.java
  src/main/java/com/example/solidconnection/application/service/ApplicationQueryService.java
  src/test/java/com/example/solidconnection/application/service/ApplicationQueryServiceTest.java
Labels: bug

#232 fix: 기타 언어 시험 유형 추가
  src/main/java/com/example/solidconnection/type/LanguageTestType.java
Labels: bug

#242 fix: language_test_type enum ETC 추가 flyway 반영
  src/main/resources/db/migration/V9__add_etc_to_language_test_type_enum.sql
Labels: bug

#240 refactor: 파견 가능학기 enum에 2개학기 추가
  src/main/java/com/example/solidconnection/type/SemesterAvailableForDispatch.java
  src/main/resources/db/migration/V8__add_two_semester_to_semeter_avaliable_enum.sql
Labels: refactor
