Repository solid-connection/solid-connect-server, pull requests merged in 2025-05, with the labels that each got.

#289 fix: 토큰 재발급 로직 수정
  src/main/java/com/example/solidconnection/auth/controller/AuthController.java
  src/main/java/com/example/solidconnection/auth/domain/TokenType.java
  src/main/java/com/example/solidconnection/auth/dto/ReissueRequest.java
  src/main/java/com/example/solidconnection/auth/service/AuthService.java
  src/main/java/com/example/solidconnection/auth/service/AuthTokenProvider.java
  src/main/java/com/example/solidconnection/util/JwtUtils.java
  src/test/java/com/example/solidconnection/auth/service/AuthServiceTest.java
Labels: 버그

#295 fix: Alloy 설정파일이 배포시에 업로드 되지 않는 오류 수정
  .github/workflows/dev-cd.yml
  .github/workflows/prod-cd.yml
  docker-compose.dev.yml
  docker-compose.prod.yml
Labels: 인프라

#303 refactor: 로그아웃, 탈퇴 시 refresh 토큰을 삭제하도록
  src/main/java/com/example/solidconnection/auth/controller/AuthController.java
  src/main/java/com/example/solidconnection/auth/service/AuthService.java
  src/main/java/com/example/solidconnection/auth/service/AuthTokenProvider.java
  src/test/java/com/example/solidconnection/auth/service/AuthServiceTest.java
  src/test/java/com/example/solidconnection/auth/service/AuthTokenProviderTest.java
Labels: 리팩터링

#305 fix: Alloy 오류 수정
  docker-compose.dev.yml
  docker-compose.prod.yml
Labels: 버그

#302 feat: News 소식지 도메인 추가
  README.md
  src/main/java/com/example/solidconnection/news/domain/News.java
  src/main/resources/db/migration/V12__create_news.sql
Labels: 기능

#309 fix: 누락한 어노테이션 추가
  src/main/java/com/example/solidconnection/auth/controller/AuthController.java
Labels: 버그

#286 refactor: 대학 관련 통합 테스트 데이터 정의 구조 개선
  build.gradle
  src/test/java/com/example/solidconnection/country/fixture/CountryFixture.java
  src/test/java/com/example/solidconnection/country/fixture/CountryFixtureBuilder.java
  src/test/java/com/example/solidconnection/country/repository/CountryRepositoryForTest.java
  src/test/java/com/example/solidconnection/region/fixture/RegionFixture.java
  src/test/java/com/example/solidconnection/region/fixture/RegionFixtureBuilder.java
  src/test/java/com/example/solidconnection/region/repository/RegionRepositoryForTest.java
  src/test/java/com/example/solidconnection/support/TestContainerSpringBootTest.java
  src/test/java/com/example/solidconnection/university/fixture/LanguageRequirementFixture.java
  src/test/java/com/example/solidconnection/university/fixture/LanguageRequirementFixtureBuilder.java
  src/test/java/com/example/solidconnection/university/fixture/UniversityFixture.java
  src/test/java/com/example/solidconnection/university/fixture/UniversityFixtureBuilder.java
  src/test/java/com/example/solidconnection/university/fixture/UniversityInfoForApplyFixture.java
  src/test/java/com/example/solidconnection/university/fixture/UniversityInfoForApplyFixtureBuilder.java
  src/test/java/com/example/solidconnection/university/service/UniversityQueryServiceTest.java
Labels: 리팩터링

#311 refactor: 회원 탈퇴 API HTTP Method를 PATCH에서 DELETE로 변경
  src/main/java/com/example/solidconnection/auth/controller/AuthController.java
Labels: 리팩터링

#313 refactor: 대학(추천, 좋아요) 통합 테스트 데이터 Fixture 메서드로 변경
  src/test/java/com/example/solidconnection/university/service/GeneralUniversityRecommendServiceTest.java
  src/test/java/com/example/solidconnection/university/service/UniversityLikeServiceTest.java
  src/test/java/com/example/solidconnection/university/service/UniversityRecommendServiceTest.java
Labels: 리팩터링

#319 refactor: 유저 관련 통합 테스트 데이터 fixture 메서드로 변경
  src/test/java/com/example/solidconnection/admin/service/AdminGpaScoreServiceTest.java
  src/test/java/com/example/solidconnection/admin/service/AdminLanguageTestScoreServiceTest.java
  src/test/java/com/example/solidconnection/auth/service/AuthServiceTest.java
  src/test/java/com/example/solidconnection/auth/service/EmailSignInServiceTest.java
  src/test/java/com/example/solidconnection/auth/service/SignInServiceTest.java
  src/test/java/com/example/solidconnection/community/post/service/PostCommandServiceTest.java
  src/test/java/com/example/solidconnection/community/post/service/PostLikeServiceTest.java
  src/test/java/com/example/solidconnection/community/post/service/PostQueryServiceTest.java
  src/test/java/com/example/solidconnection/concurrency/PostLikeCountConcurrencyTest.java
  src/test/java/com/example/solidconnection/concurrency/PostViewCountConcurrencyTest.java
  src/test/java/com/example/solidconnection/concurrency/ThunderingHerdTest.java
  src/test/java/com/example/solidconnection/custom/resolver/AuthorizedUserResolverTest.java
  src/test/java/com/example/solidconnection/custom/security/aspect/AdminAuthorizationAspectTest.java
  src/test/java/com/example/solidconnection/custom/security/provider/SiteUserAuthenticationProviderTest.java
  src/test/java/com/example/solidconnection/custom/security/userdetails/SiteUserDetailsServiceTest.java
  src/test/java/com/example/solidconnection/custom/security/userdetails/SiteUserDetailsTest.java
  src/test/java/com/example/solidconnection/score/service/ScoreServiceTest.java
  src/test/java/com/example/solidconnection/siteuser/fixture/SiteUserFixture.java
  src/test/java/com/example/solidconnection/siteuser/fixture/SiteUserFixtureBuilder.java
  src/test/java/com/example/solidconnection/siteuser/service/MyPageServiceTest.java
  src/test/java/com/example/solidconnection/siteuser/service/SiteUserServiceTest.java
  src/test/java/com/example/solidconnection/university/service/UniversityLikeServiceTest.java
  src/test/java/com/example/solidconnection/university/service/UniversityRecommendServiceTest.java
Labels: 리팩터링

#325 refactor: 성적 관련 통합 테스트 데이터 fixture 메서드로 변경
  src/test/java/com/example/solidconnection/admin/service/AdminGpaScoreServiceTest.java
  src/test/java/com/example/solidconnection/admin/service/AdminLanguageTestScoreServiceTest.java
  src/test/java/com/example/solidconnection/score/fixture/GpaScoreFixture.java
  src/test/java/com/example/solidconnection/score/fixture/GpaScoreFixtureBuilder.java
  src/test/java/com/example/solidconnection/score/fixture/LanguageTestScoreFixture.java
  src/test/java/com/example/solidconnection/score/fixture/LanguageTestScoreFixtureBuilder.java
  src/test/java/com/example/solidconnection/score/service/ScoreServiceTest.java
Labels: 리팩터링

#324 refactor: Jwt 토큰 관련 클래스를 상속이 아니라 조합하도록
  src/main/java/com/example/solidconnection/auth/service/AuthService.java
  src/main/java/com/example/solidconnection/auth/service/AuthTokenProvider.java
  src/main/java/com/example/solidconnection/auth/service/CommonSignUpTokenProvider.java
  src/main/java/com/example/solidconnection/auth/service/EmailSignUpTokenProvider.java
  src/main/java/com/example/solidconnection/auth/service/TokenProvider.java
  src/main/java/com/example/solidconnection/auth/service/oauth/OAuthSignUpTokenProvider.java
  src/main/java/com/example/solidconnection/auth/token/JwtTokenProvider.java
  src/main/java/com/example/solidconnection/auth/token/TokenBlackListService.java
  src/main/java/com/example/solidconnection/auth/token/config/JwtProperties.java
  src/main/java/com/example/solidconnection/security/filter/AuthorizationHeaderParser.java
  src/main/java/com/example/solidconnection/security/filter/BlacklistChecker.java
  src/main/java/com/example/solidconnection/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/example/solidconnection/security/filter/SignOutCheckFilter.java
  src/main/java/com/example/solidconnection/security/provider/SiteUserAuthenticationProvider.java
  src/main/java/com/example/solidconnection/util/JwtUtils.java
  src/test/java/com/example/solidconnection/auth/service/AuthServiceTest.java
  src/test/java/com/example/solidconnection/auth/service/AuthTokenProviderTest.java
  src/test/java/com/example/solidconnection/auth/service/JwtTokenProviderTest.java
  src/test/java/com/example/solidconnection/auth/service/SignInServiceTest.java
  src/test/java/com/example/solidconnection/auth/service/TokenBlackListServiceTest.java
  src/test/java/com/example/solidconnection/auth/service/oauth/OAuthSignUpTokenProviderTest.java
  src/test/java/com/example/solidconnection/security/filter/AuthorizationHeaderParserTest.java
  src/test/java/com/example/solidconnection/security/filter/JwtAuthenticationFilterTest.java
  src/test/java/com/example/solidconnection/security/filter/SignOutCheckFilterTest.java
  src/test/java/com/example/solidconnection/security/provider/SiteUserAuthenticationProviderTest.java
  src/test/java/com/example/solidconnection/util/JwtUtilsTest.java
Labels: 리팩터링
