Repository solid-connection/solid-connect-server, pull requests merged in 2025-07, with the labels that each got.

#360 refactor: @Repository 어노테이션 안붙이도록 통일
  src/main/java/com/example/solidconnection/application/repository/ApplicationRepository.java
  src/main/java/com/example/solidconnection/community/board/repository/BoardRepository.java
  src/main/java/com/example/solidconnection/community/post/repository/PostImageRepository.java
  src/main/java/com/example/solidconnection/community/post/repository/PostLikeRepository.java
  src/main/java/com/example/solidconnection/community/post/repository/PostRepository.java
  src/main/java/com/example/solidconnection/location/country/repository/CountryRepository.java
  src/main/java/com/example/solidconnection/location/country/repository/InterestedCountryRepository.java
  src/main/java/com/example/solidconnection/location/region/repository/InterestedRegionRepository.java
  src/main/java/com/example/solidconnection/location/region/repository/RegionRepository.java
  src/main/java/com/example/solidconnection/score/repository/GpaScoreRepository.java
  src/main/java/com/example/solidconnection/score/repository/LanguageTestScoreRepository.java
  src/main/java/com/example/solidconnection/siteuser/repository/SiteUserRepository.java
  src/main/java/com/example/solidconnection/university/repository/LanguageRequirementRepository.java
  src/main/java/com/example/solidconnection/university/repository/UniversityInfoForApplyRepository.java
  src/main/java/com/example/solidconnection/university/repository/UniversityRepository.java
Labels: 리팩터링

#359 feat: 소식지 좋아요 엔티티 추가
  src/main/java/com/example/solidconnection/news/domain/LikedNews.java
  src/main/resources/db/migration/V21__create_liked_news_table.sql
Labels: 기능

#362 feat: 멘토링 관련 도메인 추가
  src/main/java/com/example/solidconnection/common/exception/ErrorCode.java
  src/main/java/com/example/solidconnection/mentor/controller/MentoringController.java
  src/main/java/com/example/solidconnection/mentor/domain/Mentor.java
  src/main/java/com/example/solidconnection/mentor/domain/Mentoring.java
  src/main/java/com/example/solidconnection/mentor/dto/MentoringApplyRequest.java
  src/main/java/com/example/solidconnection/mentor/dto/MentoringApplyResponse.java
  src/main/java/com/example/solidconnection/mentor/dto/MentoringCheckResponse.java
  src/main/java/com/example/solidconnection/mentor/dto/MentoringConfirmRequest.java
  src/main/java/com/example/solidconnection/mentor/dto/MentoringConfirmResponse.java
  src/main/java/com/example/solidconnection/mentor/dto/MentoringCountResponse.java
  src/main/java/com/example/solidconnection/mentor/dto/MentoringListResponse.java
  src/main/java/com/example/solidconnection/mentor/dto/MentoringResponse.java
  src/main/java/com/example/solidconnection/mentor/repository/MentorRepository.java
  src/main/java/com/example/solidconnection/mentor/repository/MentoringRepository.java
  src/main/java/com/example/solidconnection/mentor/service/MentoringCommandService.java
  src/main/java/com/example/solidconnection/mentor/service/MentoringQueryService.java
  src/test/java/com/example/solidconnection/mentor/fixture/MentorFixture.java
  src/test/java/com/example/solidconnection/mentor/fixture/MentorFixtureBuilder.java
  src/test/java/com/example/solidconnection/mentor/fixture/MentoringFixture.java
  src/test/java/com/example/solidconnection/mentor/fixture/MentoringFixtureBuilder.java
  src/test/java/com/example/solidconnection/mentor/service/MentoringCommandServiceTest.java
  src/test/java/com/example/solidconnection/mentor/service/MentoringQueryServiceTest.java
Labels: 기능

#377 feat: 소식지 좋아요 기능 구현
  src/main/java/com/example/solidconnection/common/exception/ErrorCode.java
  src/main/java/com/example/solidconnection/news/controller/NewsController.java
  src/main/java/com/example/solidconnection/news/domain/LikedNews.java
  src/main/java/com/example/solidconnection/news/dto/LikedNewsResponse.java
  src/main/java/com/example/solidconnection/news/repository/LikedNewsRepository.java
  src/main/java/com/example/solidconnection/news/service/NewsLikeService.java
  src/test/java/com/example/solidconnection/news/service/NewsLikeServiceTest.java
Labels: 기능

#372 refactor: Community 연관관계 수정/삭제
  src/main/java/com/example/solidconnection/community/board/domain/Board.java
  src/main/java/com/example/solidconnection/community/board/repository/BoardRepository.java
  src/main/java/com/example/solidconnection/community/comment/domain/Comment.java
  src/main/java/com/example/solidconnection/community/comment/dto/CommentCreateRequest.java
  src/main/java/com/example/solidconnection/community/comment/dto/PostFindCommentResponse.java
  src/main/java/com/example/solidconnection/community/comment/service/CommentService.java
  src/main/java/com/example/solidconnection/community/post/domain/Post.java
  src/main/java/com/example/solidconnection/community/post/domain/PostLike.java
  src/main/java/com/example/solidconnection/community/post/dto/PostCreateRequest.java
  src/main/java/com/example/solidconnection/community/post/repository/PostLikeRepository.java
  src/main/java/com/example/solidconnection/community/post/repository/PostRepository.java
  src/main/java/com/example/solidconnection/community/post/service/PostCommandService.java
  src/main/java/com/example/solidconnection/community/post/service/PostLikeService.java
  src/main/java/com/example/solidconnection/community/post/service/PostQueryService.java
  src/main/java/com/example/solidconnection/siteuser/domain/SiteUser.java
  src/test/java/com/example/solidconnection/community/board/fixture/BoardFixtureBuilder.java
  src/test/java/com/example/solidconnection/community/board/repository/BoardRepositoryForTest.java
  src/test/java/com/example/solidconnection/community/comment/fixture/CommentFixtureBuilder.java
  src/test/java/com/example/solidconnection/community/comment/service/CommentServiceTest.java
  src/test/java/com/example/solidconnection/community/post/fixture/PostFixtureBuilder.java
  src/test/java/com/example/solidconnection/community/post/service/PostLikeServiceTest.java
  src/test/java/com/example/solidconnection/community/post/service/PostQueryServiceTest.java
  src/test/java/com/example/solidconnection/concurrency/PostViewCountConcurrencyTest.java
  src/test/java/com/example/solidconnection/siteuser/service/MyPageServiceTest.java
Labels: 리팩터링

#373 refactor: 댓글 정책 변경에 따른 리팩터링
  src/main/java/com/example/solidconnection/community/comment/domain/Comment.java
  src/main/java/com/example/solidconnection/community/comment/dto/PostFindCommentResponse.java
  src/main/java/com/example/solidconnection/community/comment/repository/CommentRepository.java
  src/main/java/com/example/solidconnection/community/comment/service/CommentService.java
  src/main/resources/db/migration/V22_add_is_deleted_to_comment.sql
  src/test/java/com/example/solidconnection/community/comment/service/CommentServiceTest.java
Labels: 리팩터링

#383 refactor: '좋아요'용어 통일 및 회의에서 논의된 내용 적용
  src/main/java/com/example/solidconnection/siteuser/service/MyPageService.java
  src/main/java/com/example/solidconnection/university/controller/UnivApplyInfoController.java
  src/main/java/com/example/solidconnection/university/service/LikedUnivApplyInfoService.java
  src/test/java/com/example/solidconnection/siteuser/service/MyPageServiceTest.java
  src/test/java/com/example/solidconnection/university/service/LikedUnivApplyInfoServiceTest.java
Labels: 리팩터링

#392 fix: cd 스크립트의 alloy 파일 경로 수정
  .github/workflows/dev-cd.yml
  .github/workflows/prod-cd.yml
Labels: 버그

#402 feat: 신고 기능 구현
  src/main/java/com/example/solidconnection/common/exception/ErrorCode.java
  src/main/java/com/example/solidconnection/report/controller/ReportController.java
  src/main/java/com/example/solidconnection/report/domain/Report.java
  src/main/java/com/example/solidconnection/report/domain/ReportType.java
  src/main/java/com/example/solidconnection/report/domain/TargetType.java
  src/main/java/com/example/solidconnection/report/dto/ReportRequest.java
  src/main/java/com/example/solidconnection/report/repository/ReportRepository.java
  src/main/java/com/example/solidconnection/report/service/ReportService.java
  src/main/resources/db/migration/V24__create_report_table.sql
  src/test/java/com/example/solidconnection/community/post/fixture/PostFixture.java
  src/test/java/com/example/solidconnection/report/fixture/ReportFixture.java
  src/test/java/com/example/solidconnection/report/fixture/ReportFixtureBuilder.java
  src/test/java/com/example/solidconnection/report/service/ReportServiceTest.java
Labels: 기능

#405 fix: flyway 버전 충돌 해결
  src/main/resources/db/migration/V25__create_report_table.sql
Labels: 버그

#410 fix: RequiredArgsConstructor 동작하도록 임시 수정
  src/main/java/com/example/solidconnection/security/aspect/RoleAuthorizationAspect.java
  src/test/java/com/example/solidconnection/security/aspect/RoleAuthorizationAspectTest.java
Labels: 버그

#412 refactor: 멘토 조회 시, 파견 상태 대신 '파견 학기'를 응답하도록
  src/main/java/com/example/solidconnection/mentor/domain/Mentor.java
  src/main/java/com/example/solidconnection/mentor/dto/MentorDetailResponse.java
  src/main/java/com/example/solidconnection/mentor/dto/MentorMyPageResponse.java
  src/main/java/com/example/solidconnection/mentor/dto/MentorPreviewResponse.java
  src/main/java/com/example/solidconnection/mentor/dto/MentorPreviewsResponse.java
  src/main/resources/db/migration/V26__add_term_column_to_mentor.sql
  src/test/java/com/example/solidconnection/mentor/fixture/MentorFixtureBuilder.java
Labels: 리팩터링
