Repository solid-connection/solid-connect-server, pull requests merged in 2025-08, with the labels that each got.

#422 refactor: 변경된 멘토/멘티 탭 명세에 맞게 api 수정
  src/main/java/com/example/solidconnection/mentor/controller/MentoringForMenteeController.java
  src/main/java/com/example/solidconnection/mentor/controller/MentoringForMentorController.java
  src/main/java/com/example/solidconnection/mentor/domain/Mentoring.java
  src/main/java/com/example/solidconnection/mentor/dto/CheckMentoringRequest.java
  src/main/java/com/example/solidconnection/mentor/dto/CheckedMentoringsResponse.java
  src/main/java/com/example/solidconnection/mentor/dto/MentoringForMenteeResponse.java
  src/main/java/com/example/solidconnection/mentor/dto/MentoringForMentorResponse.java
  src/main/java/com/example/solidconnection/mentor/dto/MentoringListResponse.java
  src/main/java/com/example/solidconnection/mentor/repository/MentoringRepository.java
  src/main/java/com/example/solidconnection/mentor/service/MentoringCheckService.java
  src/main/java/com/example/solidconnection/mentor/service/MentoringCommandService.java
  src/main/java/com/example/solidconnection/mentor/service/MentoringQueryService.java
  src/main/resources/db/migration/V27__add_checked_at_by_mentee_column.sql
  src/test/java/com/example/solidconnection/mentor/fixture/MentoringFixture.java
  src/test/java/com/example/solidconnection/mentor/fixture/MentoringFixtureBuilder.java
  src/test/java/com/example/solidconnection/mentor/service/MentoringCheckServiceTest.java
  src/test/java/com/example/solidconnection/mentor/service/MentoringCommandServiceTest.java
  src/test/java/com/example/solidconnection/mentor/service/MentoringQueryServiceTest.java
Labels: 리팩터링

#420 refactor: 멘토의 마이페이지 응답에 '합격 팁' 추가
  src/main/java/com/example/solidconnection/mentor/controller/MentorController.java
  src/main/java/com/example/solidconnection/mentor/dto/MentorMyPageResponse.java
Labels: 리팩터링

#426 fix: 채널 수정 시 유니크 제약 위반하지 않도록
  src/main/java/com/example/solidconnection/mentor/domain/Channel.java
  src/main/java/com/example/solidconnection/mentor/domain/Mentor.java
  src/test/java/com/example/solidconnection/mentor/service/MentorMyPageServiceTest.java
Labels: 버그

#408 feat: 채팅 기능 구현
  src/main/java/com/example/solidconnection/chat/controller/ChatController.java
  src/main/java/com/example/solidconnection/chat/domain/ChatAttachment.java
  src/main/java/com/example/solidconnection/chat/domain/ChatMessage.java
  src/main/java/com/example/solidconnection/chat/domain/ChatParticipant.java
  src/main/java/com/example/solidconnection/chat/domain/ChatReadStatus.java
  src/main/java/com/example/solidconnection/chat/domain/ChatRoom.java
  src/main/java/com/example/solidconnection/chat/dto/ChatAttachmentResponse.java
  src/main/java/com/example/solidconnection/chat/dto/ChatMessageResponse.java
  src/main/java/com/example/solidconnection/chat/dto/ChatParticipantResponse.java
  src/main/java/com/example/solidconnection/chat/dto/ChatRoomListResponse.java
  src/main/java/com/example/solidconnection/chat/dto/ChatRoomResponse.java
  src/main/java/com/example/solidconnection/chat/repository/ChatAttachmentRepository.java
  src/main/java/com/example/solidconnection/chat/repository/ChatMessageRepository.java
  src/main/java/com/example/solidconnection/chat/repository/ChatParticipantRepository.java
  src/main/java/com/example/solidconnection/chat/repository/ChatReadStatusRepository.java
  src/main/java/com/example/solidconnection/chat/repository/ChatRoomRepository.java
  src/main/java/com/example/solidconnection/chat/service/ChatService.java
  src/main/java/com/example/solidconnection/common/exception/ErrorCode.java
  src/test/java/com/example/solidconnection/chat/fixture/ChatAttachmentFixture.java
  src/test/java/com/example/solidconnection/chat/fixture/ChatAttachmentFixtureBuilder.java
  src/test/java/com/example/solidconnection/chat/fixture/ChatMessageFixture.java
  src/test/java/com/example/solidconnection/chat/fixture/ChatMessageFixtureBuilder.java
  src/test/java/com/example/solidconnection/chat/fixture/ChatParticipantFixture.java
  src/test/java/com/example/solidconnection/chat/fixture/ChatParticipantFixtureBuilder.java
  src/test/java/com/example/solidconnection/chat/fixture/ChatReadStatusFixture.java
  src/test/java/com/example/solidconnection/chat/fixture/ChatReadStatusFixtureBuilder.java
  src/test/java/com/example/solidconnection/chat/fixture/ChatRoomFixture.java
  src/test/java/com/example/solidconnection/chat/fixture/ChatRoomFixtureBuilder.java
  src/test/java/com/example/solidconnection/chat/repository/ChatReadStatusRepositoryForTest.java
  src/test/java/com/example/solidconnection/chat/service/ChatServiceTest.java
Labels: 기능

#423 feat: 채팅 메시지 송수신 구현
  src/main/java/com/example/solidconnection/chat/config/CustomHandshakeHandler.java
  src/main/java/com/example/solidconnection/chat/config/StompHandler.java
  src/main/java/com/example/solidconnection/chat/config/StompWebSocketConfig.java
  src/main/java/com/example/solidconnection/chat/config/WebSocketHandshakeInterceptor.java
  src/main/java/com/example/solidconnection/chat/controller/ChatMessageController.java
  src/main/java/com/example/solidconnection/chat/dto/ChatMessageSendRequest.java
  src/main/java/com/example/solidconnection/chat/dto/ChatMessageSendResponse.java
  src/main/java/com/example/solidconnection/chat/service/ChatService.java
  src/main/java/com/example/solidconnection/security/config/SecurityConfiguration.java
Labels: 기능

#440 test: WebSocket 관련 테스트 코드 작성
  src/test/java/com/example/solidconnection/chat/service/ChatServiceTest.java
  src/test/java/com/example/solidconnection/websocket/WebSocketStompIntegrationTest.java
Labels: 테스트

#443 refactor: 멘토의 합격 팁, 자기 소개가 null 을 허용하지 않도록
  src/main/java/com/example/solidconnection/mentor/domain/Mentor.java
  src/main/resources/db/migration/V29__alter_mentor_introduction_pass_tip_not_null.sql
Labels: 리팩터링

#448 feat: 비밀번호 변경 API 구현
  src/main/java/com/example/solidconnection/common/exception/ErrorCode.java
  src/main/java/com/example/solidconnection/siteuser/controller/MyPageController.java
  src/main/java/com/example/solidconnection/siteuser/domain/SiteUser.java
  src/main/java/com/example/solidconnection/siteuser/dto/PasswordUpdateRequest.java
  src/main/java/com/example/solidconnection/siteuser/dto/validation/PasswordConfirmation.java
  src/main/java/com/example/solidconnection/siteuser/dto/validation/PasswordConfirmationValidator.java
  src/main/java/com/example/solidconnection/siteuser/service/MyPageService.java
  src/test/java/com/example/solidconnection/siteuser/dto/validation/PasswordConfirmationValidatorTest.java
  src/test/java/com/example/solidconnection/siteuser/service/MyPageServiceTest.java
Labels: 기능

#437 feat: 마이페이지 응답 요소 추가
  src/main/java/com/example/solidconnection/location/country/repository/CountryRepository.java
  src/main/java/com/example/solidconnection/siteuser/dto/MyPageResponse.java
  src/main/java/com/example/solidconnection/siteuser/service/MyPageService.java
  src/test/java/com/example/solidconnection/siteuser/service/MyPageServiceTest.java
Labels: 기능

#452 refactor: accessToken 재발급을 refreshToken 쿠키를 통해 하도록
  src/main/java/com/example/solidconnection/auth/controller/AuthController.java
  src/main/java/com/example/solidconnection/auth/controller/RefreshTokenCookieManager.java
  src/main/java/com/example/solidconnection/auth/dto/ReissueRequest.java
  src/main/java/com/example/solidconnection/auth/service/AuthService.java
  src/main/java/com/example/solidconnection/auth/service/AuthTokenProvider.java
  src/main/java/com/example/solidconnection/auth/service/SignInService.java
  src/main/java/com/example/solidconnection/common/exception/ErrorCode.java
  src/test/java/com/example/solidconnection/auth/controller/RefreshTokenCookieManagerTest.java
  src/test/java/com/example/solidconnection/auth/service/AuthServiceTest.java
  src/test/java/com/example/solidconnection/auth/service/AuthTokenProviderTest.java
  src/test/java/com/example/solidconnection/websocket/WebSocketStompIntegrationTest.java
Labels: 리팩터링

#457 feat: 채팅방 partner 정보를 조회하는 API 추가
  src/main/java/com/example/solidconnection/chat/controller/ChatController.java
  src/main/java/com/example/solidconnection/chat/service/ChatService.java
  src/test/java/com/example/solidconnection/chat/service/ChatServiceTest.java
Labels: 기능

#463 refactor: 멘토의 멘토링 목록 조회 시 isConfirmed 대신 verifyStatus를 응답하도록
  src/main/java/com/example/solidconnection/mentor/dto/MentoringForMentorResponse.java
Labels: 리팩터링

#471 refactor: 기획 변경에 맞게 필터링 검색 기능 수정
  src/main/java/com/example/solidconnection/university/controller/UnivApplyInfoController.java
  src/main/java/com/example/solidconnection/university/domain/LanguageTestType.java
  src/main/java/com/example/solidconnection/university/dto/UnivApplyInfoFilterSearchRequest.java
  src/main/java/com/example/solidconnection/university/repository/UniversityRepository.java
  src/main/java/com/example/solidconnection/university/repository/custom/UnivApplyInfoFilterRepository.java
  src/main/java/com/example/solidconnection/university/repository/custom/UnivApplyInfoFilterRepositoryImpl.java
  src/main/java/com/example/solidconnection/university/service/UnivApplyInfoQueryService.java
  src/test/java/com/example/solidconnection/university/service/UnivApplyInfoQueryServiceTest.java
Labels: 리팩터링

#472 refactor: verify_status의 타입을 통일한다.
  src/main/java/com/example/solidconnection/application/domain/Application.java
  src/main/java/com/example/solidconnection/score/domain/GpaScore.java
  src/main/java/com/example/solidconnection/score/domain/LanguageTestScore.java
  src/main/resources/db/migration/V30__modify_verify_status_from_varchar_to_enum.sql
Labels: 리팩터링

#486 feat: 대학지원정보 텍스트 검색 기능 구현
  src/main/java/com/example/solidconnection/university/controller/UnivApplyInfoController.java
  src/main/java/com/example/solidconnection/university/repository/custom/UnivApplyInfoFilterRepository.java
  src/main/java/com/example/solidconnection/university/repository/custom/UnivApplyInfoFilterRepositoryImpl.java
  src/main/java/com/example/solidconnection/university/service/UnivApplyInfoQueryService.java
  src/test/java/com/example/solidconnection/university/fixture/UnivApplyInfoFixture.java
  src/test/java/com/example/solidconnection/university/fixture/UniversityFixture.java
  src/test/java/com/example/solidconnection/university/service/UnivApplyInfoQueryServiceTest.java
Labels: 기능

#496 fix: 지원자 현황에 대한 어드민 권한 제거
  src/main/java/com/example/solidconnection/application/controller/ApplicationController.java
Labels: 버그

#477 refactor: 채팅방 관련 n + 1 문제 개선
  src/main/java/com/example/solidconnection/chat/dto/ChatRoomData.java
  src/main/java/com/example/solidconnection/chat/dto/UnreadCountDto.java
  src/main/java/com/example/solidconnection/chat/repository/ChatMessageRepository.java
  src/main/java/com/example/solidconnection/chat/repository/ChatRoomRepository.java
  src/main/java/com/example/solidconnection/chat/service/ChatService.java
  src/main/java/com/example/solidconnection/siteuser/repository/SiteUserRepository.java
Labels: 리팩터링

#482 feat: 매칭된 멘티/멘토 정보 조회 기능 구현
  src/main/java/com/example/solidconnection/mentor/controller/MentoringForMenteeController.java
  src/main/java/com/example/solidconnection/mentor/dto/MatchedMentorResponse.java
  src/main/java/com/example/solidconnection/mentor/repository/MentoringRepository.java
  src/main/java/com/example/solidconnection/mentor/service/MentoringQueryService.java
  src/test/java/com/example/solidconnection/mentor/service/MentoringQueryServiceTest.java
Labels: 기능

#479 refactor: Token VO 적용, 제공과 저장 관심사 분리, 환경변수 사용하도록 수정
  src/main/java/com/example/solidconnection/auth/client/AppleOAuthClient.java
  src/main/java/com/example/solidconnection/auth/client/KakaoOAuthClient.java
  src/main/java/com/example/solidconnection/auth/controller/AuthController.java
  src/main/java/com/example/solidconnection/auth/controller/RefreshTokenCookieManager.java
  src/main/java/com/example/solidconnection/auth/domain/AccessToken.java
  src/main/java/com/example/solidconnection/auth/domain/RefreshToken.java
  src/main/java/com/example/solidconnection/auth/domain/SignUpToken.java
  src/main/java/com/example/solidconnection/auth/domain/Subject.java
  src/main/java/com/example/solidconnection/auth/domain/Token.java
  src/main/java/com/example/solidconnection/auth/domain/TokenType.java
  src/main/java/com/example/solidconnection/auth/dto/ReissueResponse.java
  src/main/java/com/example/solidconnection/auth/dto/SignInResponse.java
  src/main/java/com/example/solidconnection/auth/service/AccessToken.java
  src/main/java/com/example/solidconnection/auth/service/AuthService.java
  src/main/java/com/example/solidconnection/auth/service/AuthTokenProvider.java
  src/main/java/com/example/solidconnection/auth/service/RefreshToken.java
  src/main/java/com/example/solidconnection/auth/service/SignUpTokenProvider.java
  src/main/java/com/example/solidconnection/auth/service/TokenProvider.java
  src/main/java/com/example/solidconnection/auth/service/TokenStorage.java
  src/main/java/com/example/solidconnection/auth/service/oauth/OAuthService.java
  src/main/java/com/example/solidconnection/auth/service/signin/EmailSignInService.java
  src/main/java/com/example/solidconnection/auth/service/signin/SignInService.java
  src/main/java/com/example/solidconnection/auth/service/signup/EmailSignUpTokenProvider.java
  src/main/java/com/example/solidconnection/auth/service/signup/PasswordTemporaryStorage.java
  src/main/java/com/example/solidconnection/auth/service/signup/SignUpService.java
  src/main/java/com/example/solidconnection/auth/service/signup/SignUpTokenProvider.java
  src/main/java/com/example/solidconnection/auth/token/JwtTokenProvider.java
  src/main/java/com/example/solidconnection/auth/token/RedisTokenStorage.java
  src/main/java/com/example/solidconnection/auth/token/TokenBlackListService.java
  src/main/java/com/example/solidconnection/auth/token/config/TokenConfig.java
  src/main/java/com/example/solidconnection/auth/token/config/TokenProperties.java
  src/main/java/com/example/solidconnection/security/authentication/TokenAuthenticationProvider.java
  src/test/java/com/example/solidconnection/auth/controller/RefreshTokenCookieManagerTest.java
  src/test/java/com/example/solidconnection/auth/service/AuthServiceTest.java
  src/test/java/com/example/solidconnection/auth/service/AuthTokenProviderTest.java
  src/test/java/com/example/solidconnection/auth/service/JwtTokenProviderTest.java
  src/test/java/com/example/solidconnection/auth/service/TokenBlackListServiceTest.java
  src/test/java/com/example/solidconnection/auth/service/signin/EmailSignInServiceTest.java
  src/test/java/com/example/solidconnection/auth/service/signin/SignInServiceTest.java
  src/test/java/com/example/solidconnection/auth/service/signup/PasswordTemporaryStorageTest.java
  src/test/java/com/example/solidconnection/auth/service/signup/SignUpTokenProviderTest.java
  src/test/java/com/example/solidconnection/auth/token/RedisTokenStorageTest.java
  src/test/java/com/example/solidconnection/security/filter/SignOutCheckFilterTest.java
  src/test/java/com/example/solidconnection/websocket/WebSocketStompIntegrationTest.java
  src/test/resources/application.yml
Labels: 리팩터링
